services:
  - type: web
    name: placeiq-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false        # you set this manually in Render dashboard
      - key: GITHUB_TOKEN
        sync: false        # you set this manually in Render dashboard
    healthCheckPath: /health